<?xml version="1.0" encoding="utf-8"?><testsuite errors="1" failures="0" name="pytest" skips="0" tests="1" time="0.563"><testcase classname="" file="future_tests/index_test.py" name="future_tests.index_test" time="0"><error message="collection failure">/opt/conda/envs/learn-env/lib/python3.6/site-packages/_pytest/python.py:488: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/opt/conda/envs/learn-env/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
&lt;frozen importlib._bootstrap&gt;:971: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:955: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:656: in _load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:626: in _load_backward_compatible
    ???
/opt/conda/envs/learn-env/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:226: in load_module
    py.builtin.exec_(co, mod.__dict__)
future_tests/index_test.py:2: in &lt;module&gt;
    from ipynb.fs.full.index import (neighbors,
&lt;frozen importlib._bootstrap&gt;:971: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:955: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:665: in _load_unlocked
    ???
&lt;frozen importlib._bootstrap_external&gt;:674: in exec_module
    ???
/opt/conda/envs/learn-env/lib/python3.6/site-packages/ipynb/fs/full/__init__.py:43: in get_code
    return self.source_to_code(code_from_ipynb(nb), self.path)
E     File &quot;/home/proactive-map-1146/calculating-distance-lab-data-science-intro-000/index.ipynb&quot;, line 130
E       if neighbor == first_neighbor
E                                   ^
E   SyntaxError: invalid syntax</error></testcase></testsuite>